export type CheatItem = { id: string; group: string; title: string; code: string; note: string };

export const cheatItems: CheatItem[] = [
  { id: "cheat-1", group: "Основы", title: "Комментарий", code: "# это пояснение", note: "Комментарии объясняют код и не выполняются." },
  { id: "cheat-2", group: "Основы", title: "Переменная", code: "name = \"Аня\"", note: "Переменная хранит значение под именем." },
  { id: "cheat-3", group: "Основы", title: "Преобразовать в int", code: "number = int(\"42\")", note: "int превращает строку с целым числом в число." },
  { id: "cheat-4", group: "Основы", title: "Преобразовать в float", code: "price = float(\"2.5\")", note: "float нужен для дробей." },
  { id: "cheat-5", group: "Основы", title: "f-строка", code: "print(f\"Привет, {name}!\")", note: "В f-строку можно подставлять переменные в фигурных скобках." },
  { id: "cheat-6", group: "Основы", title: "Длина значения", code: "print(len(\"Python\"))", note: "len возвращает количество элементов." },
  { id: "cheat-7", group: "Основы", title: "Проверить тип", code: "print(type(value))", note: "type помогает понять, что хранится в переменной." },
  { id: "cheat-8", group: "Основы", title: "Округлить число", code: "print(round(3.14159, 2))", note: "Второй аргумент задаёт число знаков после запятой." },
  { id: "cheat-9", group: "Операторы", title: "Сравнить значения", code: "print(5 >= 3)", note: "Сравнение возвращает True или False." },
  { id: "cheat-10", group: "Операторы", title: "Логическое И", code: "if age >= 18 and has_ticket:\n    print(\"Вход\")", note: "and требует, чтобы оба условия были истинными." },
  { id: "cheat-11", group: "Операторы", title: "Логическое ИЛИ", code: "if is_admin or is_owner:\n    print(\"Доступ\")", note: "or достаточно одного истинного условия." },
  { id: "cheat-12", group: "Операторы", title: "Отрицание", code: "if not tasks:\n    print(\"Список пуст\")", note: "not меняет True на False и наоборот." },
  { id: "cheat-13", group: "Условия", title: "Короткое условие", code: "status = \"готово\" if done else \"в работе\"", note: "Тернарное выражение полезно для короткого выбора." },
  { id: "cheat-14", group: "Условия", title: "Несколько веток", code: "if score >= 9:\n    grade = \"A\"\nelif score >= 7:\n    grade = \"B\"\nelse:\n    grade = \"C\"", note: "elif добавляет промежуточную проверку." },
  { id: "cheat-15", group: "Циклы", title: "range с началом", code: "for number in range(1, 6):\n    print(number)", note: "range(1, 6) даёт числа от 1 до 5." },
  { id: "cheat-16", group: "Циклы", title: "while со счётчиком", code: "count = 0\nwhile count < 3:\n    count += 1", note: "Меняйте счётчик, чтобы цикл завершился." },
  { id: "cheat-17", group: "Циклы", title: "Пропустить шаг", code: "for number in range(5):\n    if number == 2:\n        continue\n    print(number)", note: "continue пропускает текущую итерацию." },
  { id: "cheat-18", group: "Циклы", title: "Остановить цикл", code: "for item in items:\n    if item == \"stop\":\n        break", note: "break завершает ближайший цикл." },
  { id: "cheat-19", group: "Циклы", title: "Номер и значение", code: "for index, value in enumerate(items, start=1):\n    print(index, value)", note: "enumerate добавляет порядковый номер." },
  { id: "cheat-20", group: "Циклы", title: "Идти по двум спискам", code: "for name, score in zip(names, scores):\n    print(name, score)", note: "zip объединяет последовательности по позициям." },
  { id: "cheat-21", group: "Списки", title: "Создать список", code: "tasks = [\"код\", \"сон\"]", note: "Список хранит упорядоченные значения." },
  { id: "cheat-22", group: "Списки", title: "Добавить элемент", code: "tasks.append(\"прогулка\")", note: "append добавляет значение в конец." },
  { id: "cheat-23", group: "Списки", title: "Вставить элемент", code: "tasks.insert(0, \"завтрак\")", note: "insert добавляет значение в выбранную позицию." },
  { id: "cheat-24", group: "Списки", title: "Удалить по значению", code: "tasks.remove(\"сон\")", note: "remove удаляет первое совпадение." },
  { id: "cheat-25", group: "Списки", title: "Удалить по индексу", code: "last = tasks.pop()", note: "pop возвращает и удаляет элемент." },
  { id: "cheat-26", group: "Списки", title: "Срез", code: "first_two = tasks[:2]", note: "Срез создаёт часть списка." },
  { id: "cheat-27", group: "Списки", title: "Сортировка копии", code: "ordered = sorted(numbers)", note: "sorted возвращает новый отсортированный список." },
  { id: "cheat-28", group: "Списки", title: "Списковое включение", code: "squares = [n * n for n in numbers]", note: "Краткий способ собрать новый список." },
  { id: "cheat-29", group: "Словари", title: "Создать словарь", code: "user = {\"name\": \"Аня\", \"age\": 20}", note: "Словарь хранит пары ключ-значение." },
  { id: "cheat-30", group: "Словари", title: "Получить безопасно", code: "city = user.get(\"city\", \"не указан\")", note: "get возвращает запасное значение при отсутствии ключа." },
  { id: "cheat-31", group: "Словари", title: "Добавить ключ", code: "user[\"city\"] = \"Казань\"", note: "Квадратные скобки добавляют или меняют значение." },
  { id: "cheat-32", group: "Словари", title: "Перебрать пары", code: "for key, value in user.items():\n    print(key, value)", note: "items возвращает ключ и значение вместе." },
  { id: "cheat-33", group: "Множества и кортежи", title: "Уникальные элементы", code: "tags = {\"python\", \"api\", \"python\"}", note: "Множество автоматически убирает повторы." },
  { id: "cheat-34", group: "Множества и кортежи", title: "Неизменяемая пара", code: "point = (10, 20)", note: "Кортеж подходит для постоянных значений." },
  { id: "cheat-35", group: "Функции", title: "Аргумент по умолчанию", code: "def greet(name=\"друг\"):\n    return f\"Привет, {name}\"", note: "Значение по умолчанию делает аргумент необязательным." },
  { id: "cheat-36", group: "Функции", title: "Именованные аргументы", code: "connect(host=\"localhost\", port=5432)", note: "Именованные аргументы понятнее при длинном вызове." },
  { id: "cheat-37", group: "Функции", title: "Произвольные аргументы", code: "def total(*numbers):\n    return sum(numbers)", note: "*numbers собирает позиционные аргументы в кортеж." },
  { id: "cheat-38", group: "Функции", title: "Произвольные ключи", code: "def show(**options):\n    print(options)", note: "**options собирает именованные аргументы в словарь." },
  { id: "cheat-39", group: "Функции", title: "Lambda", code: "double = lambda number: number * 2", note: "lambda удобна для короткой функции." },
  { id: "cheat-40", group: "Функции", title: "Локальная область", code: "def make_label():\n    label = \"готово\"\n    return label", note: "Переменная внутри функции видна только в ней." },
  { id: "cheat-41", group: "Файлы", title: "Открыть безопасно", code: "with open(\"notes.txt\", encoding=\"utf-8\") as file:\n    text = file.read()", note: "with сам закроет файл." },
  { id: "cheat-42", group: "Файлы", title: "Записать текст", code: "with open(\"notes.txt\", \"w\", encoding=\"utf-8\") as file:\n    file.write(\"Привет\")", note: "Режим w создаёт или перезаписывает файл." },
  { id: "cheat-43", group: "Файлы", title: "Добавить строку", code: "with open(\"log.txt\", \"a\", encoding=\"utf-8\") as file:\n    file.write(\"готово\\n\")", note: "Режим a добавляет в конец файла." },
  { id: "cheat-44", group: "Файлы", title: "Путь pathlib", code: "from pathlib import Path\npath = Path(\"data\") / \"report.json\"", note: "Оператор / собирает путь между папками." },
  { id: "cheat-45", group: "JSON и CSV", title: "Записать JSON", code: "json.dump(data, file, ensure_ascii=False, indent=2)", note: "ensure_ascii=False сохраняет кириллицу читаемой." },
  { id: "cheat-46", group: "JSON и CSV", title: "Прочитать JSON", code: "data = json.load(file)", note: "json.load превращает JSON-файл в Python-данные." },
  { id: "cheat-47", group: "JSON и CSV", title: "Прочитать CSV", code: "rows = csv.DictReader(file)", note: "DictReader отдаёт строки как словари." },
  { id: "cheat-48", group: "Ошибки", title: "Обработать ValueError", code: "try:\n    age = int(text)\nexcept ValueError:\n    age = 0", note: "Ловите именно ожидаемый тип ошибки." },
  { id: "cheat-49", group: "Ошибки", title: "Вызвать ошибку", code: "if not name:\n    raise ValueError(\"Имя обязательно\")", note: "raise сообщает о некорректных данных." },
  { id: "cheat-50", group: "Ошибки", title: "finally", code: "try:\n    work()\nfinally:\n    close()", note: "finally выполняется даже при ошибке." },
  { id: "cheat-51", group: "Модули и окружения", title: "Импорт функции", code: "from math import sqrt\nprint(sqrt(9))", note: "Импортируйте только нужную функцию, если так понятнее." },
  { id: "cheat-52", group: "Модули и окружения", title: "Виртуальное окружение", code: "# python -m venv .venv", note: "В окружении хранятся зависимости конкретного проекта." },
  { id: "cheat-53", group: "Регулярные выражения", title: "Найти цифры", code: "import re\nre.findall(r\"\\d+\", text)", note: "r-строка удобна для шаблонов." },
  { id: "cheat-54", group: "Классы", title: "Простой класс", code: "class User:\n    def __init__(self, name):\n        self.name = name", note: "self хранит данные конкретного объекта." },
  { id: "cheat-55", group: "Классы", title: "Наследование", code: "class Admin(User):\n    pass", note: "Наследник получает поведение родителя." },
  { id: "cheat-56", group: "Классы", title: "Property", code: "@property\ndef full_name(self):\n    return self.name", note: "property позволяет обращаться к методу как к полю." },
  { id: "cheat-57", group: "Типизация", title: "Аннотация функции", code: "def add(a: int, b: int) -> int:\n    return a + b", note: "Аннотации помогают IDE и проверкам типов." },
  { id: "cheat-58", group: "Типизация", title: "Список строк", code: "names: list[str] = [\"Аня\"]", note: "В современных версиях Python можно писать list[str]." },
  { id: "cheat-59", group: "Типизация", title: "Optional", code: "from typing import Optional\nname: Optional[str] = None", note: "Optional означает значение или None." },
  { id: "cheat-60", group: "Модели данных", title: "Dataclass", code: "@dataclass\nclass Task:\n    title: str\n    done: bool = False", note: "dataclass автоматически создаёт удобный __init__." },
  { id: "cheat-61", group: "Тесты", title: "Простой assert", code: "def test_add():\n    assert add(2, 3) == 5", note: "pytest находит функции, начинающиеся с test_." },
  { id: "cheat-62", group: "Тесты", title: "Параметризация", code: "@pytest.mark.parametrize(\"value\", [1, 2])", note: "Параметризация проверяет несколько случаев." },
  { id: "cheat-63", group: "Тесты", title: "Mock", code: "from unittest.mock import Mock\nclient = Mock()", note: "Mock заменяет внешний объект в тесте." },
  { id: "cheat-64", group: "Логирование", title: "Информационный лог", code: "logging.info(\"Запуск завершён\")", note: "Логи описывают ход программы без print в продакшене." },
  { id: "cheat-65", group: "Логирование", title: "Настройка уровня", code: "logging.basicConfig(level=logging.INFO)", note: "Уровень определяет, какие сообщения видны." },
  { id: "cheat-66", group: "Генераторы", title: "yield", code: "def numbers(limit):\n    for n in range(limit):\n        yield n", note: "yield отдаёт значения постепенно." },
  { id: "cheat-67", group: "Генераторы", title: "Генераторное выражение", code: "squares = (n * n for n in numbers)", note: "Круглые скобки создают ленивый генератор." },
  { id: "cheat-68", group: "Декораторы", title: "Сохранить метаданные", code: "from functools import wraps\n@wraps(func)", note: "wraps сохраняет имя и описание исходной функции." },
  { id: "cheat-69", group: "Контекст", title: "Свой контекст", code: "from contextlib import contextmanager\n@contextmanager\ndef managed():\n    yield", note: "Контекстный менеджер управляет ресурсом вокруг yield." },
  { id: "cheat-70", group: "Асинхронность", title: "async функция", code: "async def load():\n    await asyncio.sleep(1)", note: "await отдаёт управление, пока задача ждёт." },
  { id: "cheat-71", group: "Асинхронность", title: "Запуск async", code: "asyncio.run(main())", note: "asyncio.run запускает верхнюю coroutine." },
  { id: "cheat-72", group: "Асинхронность", title: "Несколько задач", code: "await asyncio.gather(load_a(), load_b())", note: "gather ждёт несколько задач одновременно." },
  { id: "cheat-73", group: "HTTP и API", title: "GET с тайм-аутом", code: "response = requests.get(url, timeout=10)", note: "Тайм-аут не даёт запросу зависнуть навсегда." },
  { id: "cheat-74", group: "HTTP и API", title: "Проверить статус", code: "response.raise_for_status()", note: "Метод превратит HTTP-ошибку в исключение." },
  { id: "cheat-75", group: "HTTP и API", title: "Параметры запроса", code: "requests.get(url, params={\"page\": 1}, timeout=10)", note: "params превращается в query-параметры URL." },
  { id: "cheat-76", group: "HTTP и API", title: "JSON-запрос", code: "requests.post(url, json=payload, timeout=10)", note: "json= сам сериализует словарь." },
  { id: "cheat-77", group: "SQLite", title: "Подключение", code: "connection = sqlite3.connect(\"app.db\")", note: "SQLite хранит небольшую базу в одном файле." },
  { id: "cheat-78", group: "SQLite", title: "Плейсхолдер", code: "cursor.execute(\"SELECT * FROM users WHERE id = ?\", (user_id,))", note: "Плейсхолдеры защищают от SQL-инъекций." },
  { id: "cheat-79", group: "Веб-автоматизация", title: "robots.txt", code: "rp.can_fetch(\"StudyBot\", url)", note: "При запрете остановитесь и ищите разрешённый API." },
  { id: "cheat-80", group: "Веб-автоматизация", title: "Сессия", code: "session = requests.Session()", note: "Session сохраняет разрешённое состояние своего аккаунта." },
  { id: "cheat-81", group: "Веб-автоматизация", title: "Cookie своего аккаунта", code: "session.cookies.set(\"theme\", \"dark\", domain=\"example.com\")", note: "Не передавайте cookies другим людям и сервисам." },
  { id: "cheat-82", group: "Веб-автоматизация", title: "Пауза", code: "time.sleep(1.5)", note: "Пауза снижает нагрузку на разрешённый сайт." },
  { id: "cheat-83", group: "Веб-автоматизация", title: "Кэш", code: "cache[url] = response.text", note: "Кэш уменьшает повторные разрешённые запросы." },
  { id: "cheat-84", group: "Веб-автоматизация", title: "Beautiful Soup", code: "title = soup.find(\"h1\").get_text(strip=True)", note: "Сначала берите текст, затем нормализуйте его." },
  { id: "cheat-85", group: "Боты и сервер", title: "Секрет из окружения", code: "token = os.getenv(\"BOT_TOKEN\")", note: "Токен не должен храниться в исходном коде." },
  { id: "cheat-86", group: "Боты и сервер", title: "Лог службы", code: "journalctl -u mybot.service -f", note: "journalctl показывает журнал systemd-службы." },
  { id: "cheat-87", group: "Боты и сервер", title: "Безопасная служба", code: "# User=botuser\n# Restart=on-failure", note: "Отдельный пользователь и перезапуск делают службу безопаснее." },
  { id: "cheat-88", group: "Поставка", title: "requirements.txt", code: "# requests==2.32.0", note: "Фиксируйте ключевые зависимости проекта." },
  { id: "cheat-89", group: "Поставка", title: "Dockerfile", code: "# FROM python:3.12-slim", note: "Dockerfile описывает воспроизводимое окружение." },
];
