export type PracticeVolume = "junior" | "middle" | "senior" | "web";

export type PracticeChallenge = {
  id: string;
  volume: PracticeVolume;
  format?: "Написать код" | "Исправить код" | "Адаптировать код" | "Предсказать результат";
  title: string;
  level: string;
  task: string;
  hint: string;
  solution: string;
  check: (code: string) => boolean;
};

const hasAll = (code: string, patterns: RegExp[]) => patterns.every((pattern) => pattern.test(code));

export const practiceVolumeLabels: Record<PracticeVolume, string> = {
  junior: "Том I · Junior",
  middle: "Том II · Middle",
  senior: "Том III · Senior",
  web: "Том IV · Веб и боты",
};

const basePracticeChallenges: PracticeChallenge[] = [
  { id: "hello", volume: "junior", title: "Поздоровайся с Python", level: "Начало", task: "Выведи на экран слово «Привет».", hint: "Нужна функция print(), а текст должен быть в кавычках.", solution: 'print("Привет")', check: (code) => /print\s*\(\s*["']Привет["']\s*\)/i.test(code) },
  { id: "variable", volume: "junior", title: "Сохрани имя", level: "Переменные", task: "Создай переменную name со своим именем, затем выведи её через print(name).", hint: "Сначала: name = " + '"Аня"' + ". Затем в print напиши name без кавычек.", solution: 'name = "Аня"\nprint(name)', check: (code) => hasAll(code, [/name\s*=\s*["'][^"']+["']/, /print\s*\(\s*name\s*\)/]) },
  { id: "condition", volume: "junior", title: "Проверь оценку", level: "Условия", task: "Создай score = 5. Если score больше или равен 5, выведи «Отлично!». ", hint: "Понадобятся score = 5, if score >= 5: и отступ перед print.", solution: 'score = 5\nif score >= 5:\n    print("Отлично!")', check: (code) => hasAll(code, [/score\s*=\s*5/, /if\s+score\s*>=\s*5\s*:/, /print\s*\(\s*["']Отлично!["']\s*\)/i]) },
  { id: "loop", volume: "junior", title: "Перебери список", level: "Циклы", task: "Создай список tasks с двумя словами и выведи каждое дело в цикле for.", hint: "Список пишется в квадратных скобках. Начало цикла: for task in tasks:.", solution: 'tasks = ["уроки", "сон"]\nfor task in tasks:\n    print(task)', check: (code) => hasAll(code, [/tasks\s*=\s*\[/, /for\s+\w+\s+in\s+tasks\s*:/, /print\s*\(\s*\w+\s*\)/]) },
  { id: "function", volume: "junior", title: "Сделай маленькую функцию", level: "Функции", task: "Напиши функцию double(number), которая возвращает number * 2.", hint: "Начни с def double(number): и внутри используй return.", solution: 'def double(number):\n    return number * 2', check: (code) => hasAll(code, [/def\s+double\s*\(\s*number\s*\)\s*:/, /return\s+number\s*\*\s*2/]) },
  { id: "list-append", volume: "junior", title: "Добавь покупку", level: "Списки", task: "Создай список shopping с «хлеб», добавь «молоко» методом append и выведи список.", hint: "Метод вызывается через точку: shopping.append(...).", solution: 'shopping = ["хлеб"]\nshopping.append("молоко")\nprint(shopping)', check: (code) => hasAll(code, [/shopping\s*=\s*\[/, /shopping\.append\s*\(/, /print\s*\(\s*shopping\s*\)/]) },
  { id: "dictionary", volume: "junior", title: "Карточка ученика", level: "Словари", task: "Создай словарь student с ключом «name», а затем выведи student[«name»].", hint: "Словарь использует фигурные скобки и пары ключ: значение.", solution: 'student = {"name": "Ира"}\nprint(student["name"])', check: (code) => hasAll(code, [/student\s*=\s*\{/, /["']name["']/, /print\s*\(\s*student\s*\[/]) },
  { id: "input-number", volume: "junior", title: "Преврати текст в число", level: "Ввод", task: "Запроси возраст через input и преврати его в целое число переменной age.", hint: "input всегда даёт текст. Оберни input в int(...).", solution: 'age = int(input("Сколько тебе лет? "))\nprint(age)', check: (code) => hasAll(code, [/age\s*=\s*int\s*\(\s*input\s*\(/, /print\s*\(\s*age\s*\)/]) },

  { id: "json-save", volume: "middle", title: "Сохрани данные в JSON", level: "Файлы и JSON", task: "Импортируй json и сохрани словарь user в файл user.json через json.dump.", hint: "Для записи открой файл с «w» через with open(...).", solution: 'import json\nuser = {"name": "Лена"}\nwith open("user.json", "w", encoding="utf-8") as file:\n    json.dump(user, file)', check: (code) => hasAll(code, [/import\s+json/, /with\s+open\s*\(/, /json\.dump\s*\(/]) },
  { id: "pathlib", volume: "middle", title: "Собери путь", level: "pathlib", task: "Импортируй Path и создай путь notes/today.txt через оператор /.", hint: "Сначала: from pathlib import Path. Путь можно складывать как папки.", solution: 'from pathlib import Path\npath = Path("notes") / "today.txt"\nprint(path)', check: (code) => hasAll(code, [/from\s+pathlib\s+import\s+Path/, /Path\s*\(/, /\/\s*["']today\.txt["']/]) },
  { id: "try-except", volume: "middle", title: "Не бойся ошибки", level: "Исключения", task: "Преобразуй text в число внутри try и в except ValueError выведи «Нужно число».", hint: "try и except заканчиваются двоеточием; строка внутри имеет отступ.", solution: 'text = "кот"\ntry:\n    number = int(text)\nexcept ValueError:\n    print("Нужно число")', check: (code) => hasAll(code, [/try\s*:/, /int\s*\(\s*text\s*\)/, /except\s+ValueError\s*:/, /print\s*\(\s*["']Нужно число["']\s*\)/]) },
  { id: "file-read", volume: "middle", title: "Прочитай заметку", level: "Файлы", task: "Открой notes.txt с кодировкой UTF-8 и прочитай текст методом read().", hint: "Удобная форма: with open(...) as file:.", solution: 'with open("notes.txt", encoding="utf-8") as file:\n    text = file.read()\nprint(text)', check: (code) => hasAll(code, [/with\s+open\s*\(/, /encoding\s*=\s*["']utf-8["']/, /\.read\s*\(\s*\)/]) },
  { id: "dataclass", volume: "middle", title: "Опиши книгу", level: "Модели данных", task: "Импортируй dataclass и создай класс Book с полями title: str и pages: int.", hint: "Перед классом поставь @dataclass.", solution: 'from dataclasses import dataclass\n\n@dataclass\nclass Book:\n    title: str\n    pages: int', check: (code) => hasAll(code, [/from\s+dataclasses\s+import\s+dataclass/, /@dataclass/, /class\s+Book\s*:/, /title\s*:\s*str/, /pages\s*:\s*int/]) },
  { id: "http-header", volume: "middle", title: "Вежливый HTTP-запрос", level: "HTTP", task: "Импортируй requests и создай headers с User-Agent для разрешённого запроса.", hint: "Словарь headers передают аргументом headers=...", solution: 'import requests\nheaders = {"User-Agent": "StudyBot/1.0"}\nresponse = requests.get("https://example.com", headers=headers, timeout=10)', check: (code) => hasAll(code, [/import\s+requests/, /headers\s*=\s*\{/, /["']User-Agent["']/, /requests\.get\s*\(/, /headers\s*=\s*headers/]) },
  { id: "sqlite-create", volume: "middle", title: "Создай таблицу", level: "SQLite", task: "Импортируй sqlite3, подключись к app.db и создай курсор.", hint: "Подключение: sqlite3.connect(...), затем connection.cursor().", solution: 'import sqlite3\nconnection = sqlite3.connect("app.db")\ncursor = connection.cursor()', check: (code) => hasAll(code, [/import\s+sqlite3/, /sqlite3\.connect\s*\(/, /\.cursor\s*\(\s*\)/]) },

  { id: "typed-function", volume: "senior", title: "Подскажи типы", level: "Типизация", task: "Напиши функцию add(a, b), у которой оба параметра и результат имеют тип int.", hint: "После параметра ставится : int, перед двоеточием функции — -> int.", solution: 'def add(a: int, b: int) -> int:\n    return a + b', check: (code) => hasAll(code, [/def\s+add\s*\(\s*a\s*:\s*int\s*,\s*b\s*:\s*int\s*\)\s*->\s*int\s*:/, /return\s+a\s*\+\s*b/]) },
  { id: "pytest", volume: "senior", title: "Проверь функцию", level: "Тесты", task: "Напиши тест test_double, который проверяет double(3) == 6.", hint: "Тестовая функция начинается с test_. Внутри используется assert.", solution: 'def test_double():\n    assert double(3) == 6', check: (code) => hasAll(code, [/def\s+test_double\s*\(\s*\)\s*:/, /assert\s+double\s*\(\s*3\s*\)\s*==\s*6/]) },
  { id: "logging", volume: "senior", title: "Запиши событие", level: "Логирование", task: "Импортируй logging, настрой basicConfig и запиши информационное сообщение.", hint: "Нужны logging.basicConfig(...) и logging.info(...).", solution: 'import logging\nlogging.basicConfig(level=logging.INFO)\nlogging.info("Программа запущена")', check: (code) => hasAll(code, [/import\s+logging/, /logging\.basicConfig\s*\(/, /logging\.info\s*\(/]) },
  { id: "generator", volume: "senior", title: "Отдавай по одному", level: "Генераторы", task: "Напиши генератор numbers, который в цикле yield отдаёт числа от 0 до limit - 1.", hint: "Внутри функции используй for number in range(limit): и yield number.", solution: 'def numbers(limit):\n    for number in range(limit):\n        yield number', check: (code) => hasAll(code, [/def\s+numbers\s*\(\s*limit\s*\)\s*:/, /for\s+number\s+in\s+range\s*\(\s*limit\s*\)\s*:/, /yield\s+number/]) },
  { id: "async-await", volume: "senior", title: "Подожди без остановки", level: "Асинхронность", task: "Импортируй asyncio и напиши async-функцию pause, которая ждёт одну секунду через await asyncio.sleep(1).", hint: "async ставится перед def, а await — перед задачей ожидания.", solution: 'import asyncio\n\nasync def pause():\n    await asyncio.sleep(1)', check: (code) => hasAll(code, [/import\s+asyncio/, /async\s+def\s+pause\s*\(\s*\)\s*:/, /await\s+asyncio\.sleep\s*\(\s*1\s*\)/]) },
  { id: "decorator", volume: "senior", title: "Оберни функцию", level: "Декораторы", task: "Напиши декоратор loud, внутри которого есть wrapper и вызов func().", hint: "Декоратор принимает func, создаёт wrapper и возвращает wrapper.", solution: 'def loud(func):\n    def wrapper():\n        print("Старт")\n        func()\n    return wrapper', check: (code) => hasAll(code, [/def\s+loud\s*\(\s*func\s*\)\s*:/, /def\s+wrapper\s*\(\s*\)\s*:/, /func\s*\(\s*\)/, /return\s+wrapper/]) },
  { id: "context-manager", volume: "senior", title: "Безопасный ресурс", level: "Контекст", task: "Импортируй contextmanager и начни функцию managed с декоратора @contextmanager и yield.", hint: "Импорт: from contextlib import contextmanager.", solution: 'from contextlib import contextmanager\n\n@contextmanager\ndef managed():\n    yield', check: (code) => hasAll(code, [/from\s+contextlib\s+import\s+contextmanager/, /@contextmanager/, /def\s+managed\s*\(\s*\)\s*:/, /yield/]) },

  { id: "robots-check", volume: "web", title: "Сначала проверь правила", level: "Этика скрапинга", task: "Сформируй URL к robots.txt для сайта example.com и выведи его. Не обходи запреты сайта.", hint: "robots.txt лежит в корне: https://site/robots.txt.", solution: 'robots_url = "https://example.com/robots.txt"\nprint(robots_url)', check: (code) => hasAll(code, [/robots_url\s*=\s*["']https:\/\/example\.com\/robots\.txt["']/, /print\s*\(\s*robots_url\s*\)/]) },
  { id: "session-cookies", volume: "web", title: "Сессия для своего аккаунта", level: "Авторизация", task: "Создай requests.Session() для разрешённой работы со своим аккаунтом и установи timeout в запросе.", hint: "Сессия создаётся так: session = requests.Session().", solution: 'import requests\nsession = requests.Session()\nresponse = session.get("https://example.com/profile", timeout=10)', check: (code) => hasAll(code, [/import\s+requests/, /requests\.Session\s*\(\s*\)/, /session\.get\s*\(/, /timeout\s*=\s*10/]) },
  { id: "rate-limit", volume: "web", title: "Пауза между запросами", level: "Бережная автоматизация", task: "Импортируй time и поставь паузу 1.5 секунды между разрешёнными запросами.", hint: "Нужна функция time.sleep(...).", solution: 'import time\n# после разрешённого запроса\ntime.sleep(1.5)', check: (code) => hasAll(code, [/import\s+time/, /time\.sleep\s*\(\s*1\.5\s*\)/]) },
  { id: "soup-title", volume: "web", title: "Найди заголовок", level: "Beautiful Soup", task: "Создай BeautifulSoup из html и найди первый h1 через find.", hint: "Импорт выглядит так: from bs4 import BeautifulSoup.", solution: 'from bs4 import BeautifulSoup\nsoup = BeautifulSoup(html, "html.parser")\ntitle = soup.find("h1")', check: (code) => hasAll(code, [/from\s+bs4\s+import\s+BeautifulSoup/, /BeautifulSoup\s*\(/, /\.find\s*\(\s*["']h1["']\s*\)/]) },
  { id: "cache", volume: "web", title: "Запомни результат", level: "Кэш", task: "Создай словарь cache, сохрани в нём ответ по ключу url и затем прочитай cache[url].", hint: "Ключ в словаре указывают в квадратных скобках.", solution: 'cache = {}\ncache[url] = response\nprint(cache[url])', check: (code) => hasAll(code, [/cache\s*=\s*\{\s*\}/, /cache\s*\[\s*url\s*\]\s*=/, /cache\s*\[\s*url\s*\]/]) },
  { id: "telegram-command", volume: "web", title: "Команда бота", level: "Telegram-бот", task: "Напиши функцию handle_start, которая возвращает приветствие пользователю бота.", hint: "Функция может принять user_name и вернуть строку через return.", solution: 'def handle_start(user_name):\n    return f"Привет, {user_name}!"', check: (code) => hasAll(code, [/def\s+handle_start\s*\(\s*user_name\s*\)\s*:/, /return\s+f["']/]) },
  { id: "env-token", volume: "web", title: "Не клади секрет в код", level: "Безопасность", task: "Импортируй os и получи BOT_TOKEN из переменной окружения через os.getenv.", hint: "Секреты не записывают прямо в исходный код; используй os.getenv(" + '"BOT_TOKEN"' + ").", solution: 'import os\nbot_token = os.getenv("BOT_TOKEN")', check: (code) => hasAll(code, [/import\s+os/, /os\.getenv\s*\(\s*["']BOT_TOKEN["']\s*\)/]) },
  { id: "extra-daily-print", volume: "junior", title: "Сообщение дня", level: "print", task: "Выведи строку «Сегодня я учусь».", hint: "Используй print с текстом в кавычках.", solution: "print(\"Сегодня я учусь\")", check: (code) => code.includes("print(") },
  { id: "extra-math-sum", volume: "junior", title: "Сложи числа", level: "Числа", task: "Создай a = 7 и b = 5, затем выведи их сумму.", hint: "Сумма записывается как a + b.", solution: "a = 7\nb = 5\nprint(a + b)", check: (code) => code.includes("a + b") },
  { id: "extra-f-string", volume: "junior", title: "Собери фразу", level: "Строки", task: "Создай name и выведи приветствие через f-строку.", hint: "Перед кавычками поставь f, а переменную помести в фигурные скобки.", solution: "name = \"Маша\"\nprint(f\"Привет, {name}!\")", check: (code) => code.includes("f\"Привет") },
  { id: "extra-boolean", volume: "junior", title: "Проверь готовность", level: "Логика", task: "Создай is_ready = True и выведи переменную.", hint: "Логические значения пишутся с большой буквы: True или False.", solution: "is_ready = True\nprint(is_ready)", check: (code) => code.includes("is_ready") },
  { id: "extra-if-else", volume: "junior", title: "Выбери статус", level: "Условия", task: "Создай age = 12. Если age >= 10, выведи «Можно», иначе «Позже».", hint: "После if и else нужны двоеточия и отступы.", solution: "age = 12\nif age >= 10:\n    print(\"Можно\")\nelse:\n    print(\"Позже\")", check: (code) => code.includes("else:") },
  { id: "extra-elif", volume: "junior", title: "Оценка буквами", level: "Условия", task: "Для score = 8 сделай ветки if, elif и else.", hint: "elif добавляет промежуточную проверку.", solution: "score = 8\nif score >= 9:\n    print(\"A\")\nelif score >= 7:\n    print(\"B\")\nelse:\n    print(\"C\")", check: (code) => code.includes("elif") },
  { id: "extra-range-loop", volume: "junior", title: "Посчитай шаги", level: "Циклы", task: "Выведи числа от 0 до 2 через range.", hint: "Нужна конструкция for number in range(3):.", solution: "for number in range(3):\n    print(number)", check: (code) => code.includes("range(3)") },
  { id: "extra-while-loop", volume: "junior", title: "Счётчик", level: "Циклы", task: "Создай count = 0 и увеличь его в цикле while.", hint: "Не забудь менять count внутри цикла.", solution: "count = 0\nwhile count < 3:\n    print(count)\n    count += 1", check: (code) => code.includes("while") },
  { id: "extra-list-index", volume: "junior", title: "Первый элемент", level: "Списки", task: "Создай список colors и выведи первый элемент.", hint: "У первого элемента индекс 0.", solution: "colors = [\"синий\", \"зелёный\"]\nprint(colors[0])", check: (code) => code.includes("colors[0]") },
  { id: "extra-list-slice", volume: "junior", title: "Часть списка", level: "Списки", task: "Выведи первые два элемента списка nums через срез.", hint: "Срез до второго индекса: nums[:2].", solution: "nums = [1, 2, 3, 4]\nprint(nums[:2])", check: (code) => code.includes("[:2]") },
  { id: "extra-list-pop", volume: "junior", title: "Убери последний", level: "Списки", task: "Создай tasks и удали последний элемент методом pop.", hint: "pop() без аргумента удаляет последний элемент.", solution: "tasks = [\"код\", \"отдых\"]\ntasks.pop()\nprint(tasks)", check: (code) => code.includes(".pop(") },
  { id: "extra-dict-update", volume: "junior", title: "Обнови профиль", level: "Словари", task: "Создай profile и добавь в него ключ city.", hint: "Новое значение: profile[\"city\"] = \"Казань\".", solution: "profile = {\"name\": \"Аня\"}\nprofile[\"city\"] = \"Казань\"\nprint(profile)", check: (code) => code.includes("[\"city\"]") },
  { id: "extra-dict-items", volume: "junior", title: "Перебери пары", level: "Словари", task: "Перебери словарь settings через items().", hint: "Для пары ключ-значение используйте for key, value in settings.items().", solution: "settings = {\"theme\": \"dark\"}\nfor key, value in settings.items():\n    print(key, value)", check: (code) => code.includes(".items(") },
  { id: "extra-set-unique", volume: "junior", title: "Убери повторы", level: "Множества", task: "Создай множество tags с повторяющимся словом.", hint: "Множество создаётся фигурными скобками.", solution: "tags = {\"python\", \"python\", \"code\"}\nprint(tags)", check: (code) => code.includes("tags =") },
  { id: "extra-tuple-point", volume: "junior", title: "Координата", level: "Кортежи", task: "Создай кортеж point из двух чисел и выведи его.", hint: "Кортеж: point = (3, 5).", solution: "point = (3, 5)\nprint(point)", check: (code) => code.includes("point = (") },
  { id: "extra-function-greet", volume: "junior", title: "Функция приветствия", level: "Функции", task: "Напиши функцию greet(name), которая печатает приветствие.", hint: "Функция начинается с def.", solution: "def greet(name):\n    print(f\"Привет, {name}!\")", check: (code) => code.includes("def greet") },
  { id: "extra-return-square", volume: "junior", title: "Верни квадрат", level: "Функции", task: "Напиши square(number), возвращающую квадрат числа.", hint: "Используйте return number * number.", solution: "def square(number):\n    return number * number", check: (code) => code.includes("return") },
  { id: "extra-input-name", volume: "junior", title: "Спроси имя", level: "Ввод", task: "Запроси имя через input и выведи его.", hint: "Ответ input сохраните в name.", solution: "name = input(\"Имя: \")\nprint(name)", check: (code) => code.includes("input(") },
  { id: "extra-comprehension", volume: "middle", title: "Квадраты чисел", level: "Коллекции", task: "Создай список квадратов для numbers через list comprehension.", hint: "Внутри квадратных скобок можно написать выражение и for.", solution: "numbers = [1, 2, 3]\nsquares = [number * number for number in numbers]\nprint(squares)", check: (code) => code.includes("for number in") },
  { id: "extra-enumerate", volume: "middle", title: "Нумеруй дела", level: "Коллекции", task: "Перебери tasks с номером через enumerate.", hint: "enumerate возвращает индекс и значение.", solution: "tasks = [\"код\", \"сон\"]\nfor index, task in enumerate(tasks, start=1):\n    print(index, task)", check: (code) => code.includes("enumerate(") },
  { id: "extra-zip", volume: "middle", title: "Склей пары", level: "Коллекции", task: "Объедини names и scores через zip.", hint: "zip идёт по двум последовательностям сразу.", solution: "names = [\"Аня\", \"Ира\"]\nscores = [5, 4]\nfor name, score in zip(names, scores):\n    print(name, score)", check: (code) => code.includes("zip(") },
  { id: "extra-sorted-key", volume: "middle", title: "Отсортируй слова", level: "Коллекции", task: "Отсортируй words по длине.", hint: "В sorted можно передать key=len.", solution: "words = [\"код\", \"проект\", \"API\"]\nprint(sorted(words, key=len))", check: (code) => code.includes("sorted(") },
  { id: "extra-json-load", volume: "middle", title: "Прочитай JSON", level: "Файлы и JSON", task: "Импортируй json и прочитай данные через json.load.", hint: "Для чтения открой файл с «r» или без режима.", solution: "import json\nwith open(\"user.json\", encoding=\"utf-8\") as file:\n    user = json.load(file)", check: (code) => code.includes("json.load") },
  { id: "extra-csv-reader", volume: "middle", title: "Прочитай CSV", level: "Файлы и CSV", task: "Импортируй csv и создай DictReader.", hint: "CSV удобно читать через csv.DictReader(file).", solution: "import csv\nwith open(\"data.csv\", encoding=\"utf-8\") as file:\n    rows = csv.DictReader(file)", check: (code) => code.includes("DictReader") },
  { id: "extra-path-exists", volume: "middle", title: "Проверь путь", level: "pathlib", task: "Создай Path и выведи результат exists().", hint: "Метод exists проверяет наличие файла.", solution: "from pathlib import Path\npath = Path(\"notes.txt\")\nprint(path.exists())", check: (code) => code.includes(".exists(") },
  { id: "extra-raise-error", volume: "middle", title: "Сообщи об ошибке", level: "Исключения", task: "Если name пустое, вызови ValueError.", hint: "Используйте raise ValueError(\"...\").", solution: "name = \"\"\nif not name:\n    raise ValueError(\"Имя нужно\")", check: (code) => code.includes("raise ValueError") },
  { id: "extra-finally", volume: "middle", title: "Закрой ресурс", level: "Исключения", task: "Добавь блок finally к try/except.", hint: "finally выполняется независимо от ошибки.", solution: "try:\n    number = int(\"7\")\nexcept ValueError:\n    print(\"Ошибка\")\nfinally:\n    print(\"Готово\")", check: (code) => code.includes("finally:") },
  { id: "extra-logging-warning", volume: "middle", title: "Предупреждение в логах", level: "Логирование", task: "Выведи warning через logging.", hint: "После import logging вызови logging.warning.", solution: "import logging\nlogging.warning(\"Мало данных\")", check: (code) => code.includes("logging.warning") },
  { id: "extra-dataclass-default", volume: "middle", title: "Модель со значением", level: "Модели данных", task: "Создай dataclass Task с done: bool = False.", hint: "Поле по умолчанию указывается после типа.", solution: "from dataclasses import dataclass\n@dataclass\nclass Task:\n    title: str\n    done: bool = False", check: (code) => code.includes("@dataclass") },
  { id: "extra-requests-params", volume: "middle", title: "Передай параметры", level: "HTTP", task: "Создай params и передай их requests.get.", hint: "Параметры запроса передаются как params=params.", solution: "import requests\nparams = {\"page\": 1}\nresponse = requests.get(\"https://example.com\", params=params, timeout=10)", check: (code) => code.includes("params=") },
  { id: "extra-requests-status", volume: "middle", title: "Проверь ответ", level: "HTTP", task: "После запроса вызови raise_for_status().", hint: "Метод находится у response.", solution: "response.raise_for_status()", check: (code) => code.includes("raise_for_status") },
  { id: "extra-sqlite-insert", volume: "middle", title: "Добавь запись", level: "SQLite", task: "Выполни INSERT с плейсхолдером ?. ", hint: "Значения передаются вторым аргументом execute.", solution: "cursor.execute(\"INSERT INTO notes(text) VALUES (?)\", (\"учусь\",))\nconnection.commit()", check: (code) => code.includes("INSERT INTO") },
  { id: "extra-module-import", volume: "middle", title: "Импорт модуля", level: "Модули", task: "Импортируй функцию sqrt из math и выведи sqrt(9).", hint: "Нужен from math import sqrt.", solution: "from math import sqrt\nprint(sqrt(9))", check: (code) => code.includes("from math import") },
  { id: "extra-venv-command", volume: "middle", title: "Создай окружение", level: "Инструменты", task: "Напиши команду создания .venv как комментарий.", hint: "В шпаргалке используется python -m venv .venv.", solution: "# python -m venv .venv", check: (code) => code.includes("venv") },
  { id: "extra-typing-list", volume: "middle", title: "Тип списка", level: "Типизация", task: "Объяви переменную names как list[str].", hint: "После имени ставят : list[str].", solution: "names: list[str] = [\"Аня\", \"Ира\"]", check: (code) => code.includes("list[str]") },
  { id: "extra-re-compile", volume: "middle", title: "Шаблон поиска", level: "Регулярные выражения", task: "Импортируй re и скомпилируй шаблон цифр.", hint: "Используйте re.compile(r\"...\").", solution: "import re\npattern = re.compile(r\"\\d+\")", check: (code) => code.includes("re.compile") },
  { id: "extra-optional-type", volume: "senior", title: "Необязательное значение", level: "Типизация", task: "Импортируй Optional и укажи Optional[str].", hint: "Optional находится в typing.", solution: "from typing import Optional\nname: Optional[str] = None", check: (code) => code.includes("Optional") },
  { id: "extra-protocol", volume: "senior", title: "Контракт объекта", level: "Типизация", task: "Импортируй Protocol и начни класс Writer(Protocol).", hint: "Protocol описывает нужные методы без наследования реализации.", solution: "from typing import Protocol\nclass Writer(Protocol):\n    def write(self, text: str) -> None: ...", check: (code) => code.includes("Protocol") },
  { id: "extra-pytest-parametrize", volume: "senior", title: "Проверь несколько случаев", level: "Тесты", task: "Добавь декоратор pytest.mark.parametrize.", hint: "Сначала импортируйте pytest.", solution: "import pytest\n@pytest.mark.parametrize(\"value\", [1, 2])\ndef test_positive(value):\n    assert value > 0", check: (code) => code.includes("parametrize") },
  { id: "extra-pytest-fixture", volume: "senior", title: "Подготовь данные", level: "Тесты", task: "Создай fixture sample_user.", hint: "Фикстура помечается @pytest.fixture.", solution: "import pytest\n@pytest.fixture\ndef sample_user():\n    return {\"name\": \"Аня\"}", check: (code) => code.includes("@pytest.fixture") },
  { id: "extra-mock", volume: "senior", title: "Подмени внешний вызов", level: "Тесты", task: "Импортируй Mock и создай mock_response.", hint: "Mock позволяет тестировать без сети.", solution: "from unittest.mock import Mock\nmock_response = Mock()", check: (code) => code.includes("Mock") },
  { id: "extra-generator-expression", volume: "senior", title: "Ленивые квадраты", level: "Генераторы", task: "Создай генератор квадратов через круглые скобки.", hint: "От списка он отличается круглыми скобками.", solution: "numbers = [1, 2, 3]\nsquares = (number * number for number in numbers)", check: (code) => code.includes("for number in") },
  { id: "extra-yield-from", volume: "senior", title: "Передай поток", level: "Генераторы", task: "Напиши генератор, который использует yield from values.", hint: "yield from передаёт элементы другой последовательности.", solution: "def stream(values):\n    yield from values", check: (code) => code.includes("yield from") },
  { id: "extra-async-gather", volume: "senior", title: "Запусти ожидания вместе", level: "Асинхронность", task: "Вызови asyncio.gather для двух задач.", hint: "gather ждёт несколько coroutine.", solution: "await asyncio.gather(task_one(), task_two())", check: (code) => code.includes("asyncio.gather") },
  { id: "extra-async-main", volume: "senior", title: "Точка входа async", level: "Асинхронность", task: "Запусти main через asyncio.run.", hint: "asyncio.run(main()) запускает верхнюю coroutine.", solution: "asyncio.run(main())", check: (code) => code.includes("asyncio.run") },
  { id: "extra-decorator-wraps", volume: "senior", title: "Сохрани имя функции", level: "Декораторы", task: "Импортируй wraps и добавь @wraps(func).", hint: "wraps помогает отладке и документации.", solution: "from functools import wraps\n@wraps(func)\ndef wrapper():\n    return func()", check: (code) => code.includes("@wraps") },
  { id: "extra-context-open", volume: "senior", title: "Контекст файла", level: "Контекст", task: "Открой файл через with open.", hint: "Контекст сам закроет ресурс.", solution: "with open(\"data.txt\", encoding=\"utf-8\") as file:\n    text = file.read()", check: (code) => code.includes("with open") },
  { id: "extra-frozen-model", volume: "senior", title: "Неизменяемая модель", level: "Модели данных", task: "Создай dataclass с frozen=True.", hint: "Параметр frozen делает объект неизменяемым.", solution: "from dataclasses import dataclass\n@dataclass(frozen=True)\nclass Config:\n    host: str", check: (code) => code.includes("frozen=True") },
  { id: "extra-dependency-injection", volume: "senior", title: "Передай зависимость", level: "Архитектура", task: "Передай repository аргументом функции save_user.", hint: "Зависимость лучше передавать явно.", solution: "def save_user(user, repository):\n    repository.save(user)", check: (code) => code.includes("repository") },
  { id: "extra-config-env", volume: "senior", title: "Конфигурация среды", level: "Конфигурация", task: "Получить MODE из окружения через getenv.", hint: "Добавьте значение по умолчанию.", solution: "import os\nmode = os.getenv(\"MODE\", \"dev\")", check: (code) => code.includes("os.getenv") },
  { id: "extra-package-init", volume: "senior", title: "Экспорт пакета", level: "Пакеты", task: "Напиши комментарий про __init__.py.", hint: "Файл __init__.py отмечает или настраивает пакет.", solution: "# package/__init__.py", check: (code) => code.includes("__init__") },
  { id: "extra-profile", volume: "senior", title: "Измерь время", level: "Производительность", task: "Импортируй time и сохрани время start.", hint: "Используйте time.perf_counter().", solution: "import time\nstart = time.perf_counter()", check: (code) => code.includes("perf_counter") },
  { id: "extra-lru-cache", volume: "senior", title: "Кэшируй функцию", level: "Производительность", task: "Импортируй lru_cache и добавь декоратор.", hint: "lru_cache находится в functools.", solution: "from functools import lru_cache\n@lru_cache\ndef fib(n):\n    return n", check: (code) => code.includes("@lru_cache") },
  { id: "extra-dockerfile", volume: "senior", title: "Образ приложения", level: "Поставка", task: "Напиши строку FROM python:3.12-slim как комментарий.", hint: "Dockerfile начинает с FROM.", solution: "# FROM python:3.12-slim", check: (code) => code.includes("FROM python") },
  { id: "extra-url-parse", volume: "web", title: "Разбери URL", level: "URL", task: "Импортируй urlparse и получи hostname адреса.", hint: "urlparse находится в urllib.parse.", solution: "from urllib.parse import urlparse\nprint(urlparse(\"https://example.com/news\").hostname)", check: (code) => code.includes("urlparse") },
  { id: "extra-robots-agent", volume: "web", title: "Имя клиента", level: "Этика скрапинга", task: "Создай user_agent с понятным именем учебного клиента.", hint: "Представляйтесь честно и добавляйте контакт в реальном проекте.", solution: "user_agent = \"StudyBot/1.0 (+contact@example.com)\"", check: (code) => code.includes("StudyBot") },
  { id: "extra-headers-accept", volume: "web", title: "Заголовок Accept", level: "HTTP", task: "Создай headers с Accept: application/json.", hint: "Заголовки хранятся в словаре.", solution: "headers = {\"Accept\": \"application/json\"}", check: (code) => code.includes("Accept") },
  { id: "extra-query-params", volume: "web", title: "Параметры поиска", level: "HTTP", task: "Создай params для поискового запроса.", hint: "Используйте словарь с q и page.", solution: "params = {\"q\": \"python\", \"page\": 1}", check: (code) => code.includes("params =") },
  { id: "extra-session-header", volume: "web", title: "Заголовок сессии", level: "Авторизация", task: "Обнови заголовки разрешённой requests.Session.", hint: "Работайте только с собственным аккаунтом.", solution: "import requests\nsession = requests.Session()\nsession.headers.update({\"User-Agent\": \"StudyBot/1.0\"})", check: (code) => code.includes("session.headers") },
  { id: "extra-cookie-own", volume: "web", title: "Cookie своего аккаунта", level: "Авторизация", task: "Покажи установку cookie на домене example.com.", hint: "Не сохраняйте чужие cookies и не передавайте их.", solution: "session.cookies.set(\"theme\", \"dark\", domain=\"example.com\")", check: (code) => code.includes("cookies.set") },
  { id: "extra-cache-key", volume: "web", title: "Ключ кэша", level: "Кэш", task: "Создай ключ кэша из URL.", hint: "Для начала достаточно cache_key = url.", solution: "cache_key = url\ncache[cache_key] = response", check: (code) => code.includes("cache_key") },
  { id: "extra-cache-ttl", volume: "web", title: "Срок кэша", level: "Кэш", task: "Сохрани время кэша через time.time().", hint: "TTL сравнивают с текущим временем.", solution: "import time\ncached_at = time.time()", check: (code) => code.includes("time.time") },
  { id: "extra-backoff", volume: "web", title: "Пауза повтора", level: "Надёжность", task: "Посчитай delay как attempt * 2.", hint: "Повышайте паузу постепенно.", solution: "attempt = 3\ndelay = attempt * 2\nprint(delay)", check: (code) => code.includes("delay =") },
  { id: "extra-status-stop", volume: "web", title: "Остановись при 429", level: "Надёжность", task: "Проверь response.status_code == 429 и выведи паузу.", hint: "429 значит, что надо замедлиться или остановиться.", solution: "if response.status_code == 429:\n    print(\"Пауза\")", check: (code) => code.includes("429") },
  { id: "extra-soup-select", volume: "web", title: "Выбери ссылку", level: "Beautiful Soup", task: "Найди ссылку CSS-селектором a.article.", hint: "Используйте soup.select_one.", solution: "link = soup.select_one(\"a.article\")", check: (code) => code.includes("select_one") },
  { id: "extra-soup-text", volume: "web", title: "Получи текст", level: "Beautiful Soup", task: "Получи текст заголовка через get_text(strip=True).", hint: "strip=True убирает лишние пробелы.", solution: "title = soup.find(\"h1\").get_text(strip=True)", check: (code) => code.includes("get_text") },
  { id: "extra-json-payload", volume: "web", title: "JSON для API", level: "API", task: "Создай payload и отправь его аргументом json=.", hint: "Для JSON API используйте json=payload.", solution: "payload = {\"text\": \"Привет\"}\nresponse = requests.post(\"https://example.com/api\", json=payload, timeout=10)", check: (code) => code.includes("json=payload") },
  { id: "extra-telegram-reply", volume: "web", title: "Ответ бота", level: "Боты", task: "Сформируй словарь ответа с chat_id и text.", hint: "Бот отвечает только в разрешённом диалоге.", solution: "reply = {\"chat_id\": 1, \"text\": \"Готово\"}", check: (code) => code.includes("chat_id") },
  { id: "extra-log-request", volume: "web", title: "Лог запроса", level: "Наблюдаемость", task: "Запиши URL и статус через logging.info.", hint: "Логи помогают видеть ошибки без секретов.", solution: "import logging\nlogging.info(\"URL=%s status=%s\", url, status)", check: (code) => code.includes("logging.info") },
  { id: "extra-sqlite-state", volume: "web", title: "Состояние бота", level: "Хранение", task: "Создай SQLite-подключение для состояния бота.", hint: "SQLite подходит для маленького личного бота.", solution: "import sqlite3\nconnection = sqlite3.connect(\"bot.db\")", check: (code) => code.includes("sqlite3.connect") },
  { id: "extra-systemd-user", volume: "web", title: "Пользователь службы", level: "Сервер", task: "Напиши строку User=botuser как комментарий.", hint: "Служба должна работать от отдельного пользователя.", solution: "# User=botuser", check: (code) => code.includes("User=botuser") },
  { id: "extra-healthcheck", volume: "web", title: "Проверка здоровья", level: "Сервер", task: "Выведи короткий healthcheck-статус.", hint: "Проверка может вернуть строку «ok».", solution: "status = \"ok\"\nprint(status)", check: (code) => code.includes("status =") },
];

const trainingFormats: Array<{
  format: NonNullable<PracticeChallenge["format"]>;
  intro: string;
  hintPrefix: string;
}> = [
  { format: "Написать код", intro: "Напишите решение с нуля. ", hintPrefix: "Сначала составьте короткий план. " },
  { format: "Исправить код", intro: "Представьте, что в похожем фрагменте пропущен важный шаг: напишите исправленный вариант. ", hintPrefix: "Сверьте обязательные элементы конструкции. " },
  { format: "Адаптировать код", intro: "Примените ту же идею в небольшом личном сценарии и напишите рабочий вариант. ", hintPrefix: "Измените данные, но сохраните основную конструкцию. " },
];

const generatedPracticeChallenges: PracticeChallenge[] = basePracticeChallenges.flatMap((challenge) =>
  trainingFormats.map((variant, index) => ({
    ...challenge,
    id: `drill-${challenge.id}-${index + 1}`,
    format: variant.format,
    title: `${challenge.title} · ${variant.format.toLowerCase()}`,
    task: `${variant.intro}${challenge.task}`,
    hint: `${variant.hintPrefix}${challenge.hint}`,
  })),
);

export const practiceChallenges: PracticeChallenge[] = [...basePracticeChallenges, ...generatedPracticeChallenges];

export function evaluatePractice(challenge: PracticeChallenge, code: string) {
  if (!code.trim()) return { correct: false, message: "Сначала напишите хотя бы одну строку кода." };
  if (challenge.check(code)) return { correct: true, message: "Верно! Все важные шаги на месте. Вы только что написали рабочую идею самостоятельно." };
  return { correct: false, message: "Пока не совпало. Проверьте цель задания, отступы и подсказку; потом попробуйте ещё раз." };
}
